config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations'}

  root to: "questions#index"
  get :search, to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me,  on: :collection
      end

      resources :questions, only: %i[index show create update destroy] , shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :attachments, only: %i[destroy]
  resources :links,       only: %i[destroy]
  resources :awards,      only: %i[index destroy]

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_cancel
    end
  end

  resources :questions, concerns: [:votable] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, concerns: [:votable], only: %i[create update edit destroy], shallow: true do
      member do
        patch :best
      end
      resources :comments, only: %i[create], defaults: { commentable: 'answer'}
    end
    resources :comments, only: %i[create], defaults: { commentable: 'question'}
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one  :award, dependent: :destroy
  belongs_to :best_answer, class_name: 'Answer', optional: true
  belongs_to :user
  has_many :subscriptions, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :award, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :title, :body, presence: true

  after_create :subscribe_author

  default_scope { order(updated_at: :desc) }

  def other_answers
    answers.where.not(id: best_answer_id)
  end

  private

  def subscribe_author
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  
  before_action :set_question, only: %i[destroy update show]

  authorize_resource class: Question

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.destroy
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :question, only: %i[destroy edit]
  before_action :set_subscription, only: %i[show update]
  helper_method :question
  after_action  :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
    @award = Award.new
  end

  def show
    @new_answer = Answer.new
    @link = @new_answer.links.new
    question
    gon.current_user_id = current_user&.id
  end

  def new
    @link = question.links.new
    @award = question.build_award
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)
    attach_files(@question)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      @link = question.links.new
      @award = question.build_award
      render :new
    end
  end

  def update
    @questions = Question.all
    question.update(question_params)
    attach_files(question)
  end

  def destroy
    @question.best_answer&.unmark_as_best
    @question.destroy
    flash[:notice] = 'Your question was successfully deleted.'
    redirect_to root_path
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: %i[id name url _destroy],
                                                    award_attributes: %i[id title image _destroy])
  end

  def attach_files(question)
    question.files.attach(params[:question][:files]) if params[:question][:files].present?
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions',
                                 { question: @question, created: @question.created_at.to_date, user: @question.user.email })
  end

  def set_subscription
    @subscription ||= current_user&.subscriptions&.find_by(question: question)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
-if can? :edit, question

  = link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id}

  div class = "award-#{question.id} d-none"
    = render partial: 'awards/awards', locals: {question: question }

  div class = "attachments-#{question.id} d-none"
    = render partial: 'attachments/attachments', locals: { resource: question }

  div class = "links-#{question.id} d-none"
    = render partial: 'links/links', locals: { resource: question }

  = form_with model: question, local: false, class: 'd-none', html: {id: "edit-question-#{question.id}"} do |f|
    p
      = f.label :title, 'Title'
      = f.text_field :title
    p
      = f.label :body, 'Your question'
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true
    p
    #links
      .actions
        = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

    p= f.submit 'Save'

  = link_to 'Delete question', question_path(question), method: :delete

app/views/questions/_question.html.slim
div class = "question-#{question.id}"

  .collection-item
    pre = link_to question.title, question_path(question)

  = render partial: 'questions/form', locals: { question: question }

app/views/questions/index.html.slim
-cache collection_cache_key_for(:question)
  p
    h1.text-success
      ' Questions
      -if can? :create, Question
        => link_to new_question_path, id: 'new_question_link' do
          = octicon "plus-circle", height: 30

  .questions
    - if @questions.any?
      .question-errors
        = render 'shared/errors', resource: question
        = render @questions
    - else
      .center No questions found

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'links/link_fields', f: link
    .actions
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p
    = f.fields_for :award do |a|
      p
        = a.label :title, 'Award title'
        = a.text_field :title
      p
        = a.label :image
        = a.file_field :image

  p= f.submit 'Ask'

app/views/questions/show.html.slim
- cache @question do
-if can? :destroy, @question
  = link_to 'Delete question', question_path(@question), method: :delete

h1= @question.title
p= @question.body

= render 'shared/vote', resource: @question

.subscription
  -if can? :create, Subscription
    = render 'subscriptions/subscription', question: @question

div class = "attachments-#{@question.id}"
  = render partial: 'attachments/attachments', locals: { resource: @question }

div class = "links-#{@question.id}"
  = render partial: 'links/links', locals: { resource: @question}

div class = "comments-#{@question.id}"
  = render partial: 'comments/comments', locals: { resource: @question}

.answers
  -if @question.best_answer
    = render partial: 'answers/best_answer', object: @question.best_answer
  = render partial:'answers/answer', collection: @question.other_answers, as: :answer

.answer-errors
  = render 'shared/errors', resource: @new_answer

= form_with model: [@question, @new_answer], local: false, class: 'new-answer', data:{ type: :json } do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p
  #links
    = f.fields_for :links do |link|
    .actions
      = link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit 'Post answer'

app/views/questions/update.js.erb
$('.question-errors').html("<%= render 'shared/errors', resource: question %>")

<% if !question.errors.present? %>
  $('.questions').html('<%= j render @questions %>')
<%end%>