config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations'}

  root to: "questions#index"
  get :search, to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me,  on: :collection
      end

      resources :questions, only: %i[index show create update destroy] , shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :attachments, only: %i[destroy]
  resources :links,       only: %i[destroy]
  resources :awards,      only: %i[index destroy]

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_cancel
    end
  end

  resources :questions, concerns: [:votable] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, concerns: [:votable], only: %i[create update edit destroy], shallow: true do
      member do
        patch :best
      end
      resources :comments, only: %i[create], defaults: { commentable: 'answer'}
    end
    resources :comments, only: %i[create], defaults: { commentable: 'question'}
  end

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_load_and_authorize_resource

  def search
    @query = params[:query]
    @resource = params[:resource]
    @search_result = model_klass(@resource).search(@query) if @query
  end

  private

  def model_klass(class_name)
    class_name == 'all' ? ThinkingSphinx : class_name.classify.constantize
  end
end

app/views/search/_answer.html.slim
p = link_to resource.body.truncate(25), question_path(resource.question)

app/views/search/_comment.html.slim
- if resource.commentable.is_a? Question
  p = link_to resource.body.truncate(25), question_path(resource.commentable)
- else
  p = link_to resource.body.truncate(25), question_path(resource.commentable.question)

app/views/search/_form.html.slim
= form_with url: search_path, class: 'form-search form-inline', method: :get do |form|
    = form.text_field :query, placeholder: 'Search...', class: 'input-large search-query'
    = form.select :resource, ['all', 'question', 'answer', 'comment', 'user']
    = form.submit 'Find it!', class: 'btn btn-info'

app/views/search/_question.html.slim
p = link_to resource.title, question_path(resource)

app/views/search/_user.html.slim
.user
  p user
  = resource.email
  p admin
  =resource.admin

app/views/search/search.html.slim
h2 Search results

.search-results
  - if @resource == 'all'
    - @search_result.each do |result|
      = render "search/#{result.class.to_s.downcase}", resource: result
  - else
    - @search_result.each do |result|
      = render "search/#{@resource}", resource: result