config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', registrations: 'oauth_registrations'}

  root to: "questions#index"
  get :search, to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me,  on: :collection
      end

      resources :questions, only: %i[index show create update destroy] , shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  resources :attachments, only: %i[destroy]
  resources :links,       only: %i[destroy]
  resources :awards,      only: %i[index destroy]

  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
      patch :vote_cancel
    end
  end

  resources :questions, concerns: [:votable] do
    resources :subscriptions, only: %i[create destroy], shallow: true
    resources :answers, concerns: [:votable], only: %i[create update edit destroy], shallow: true do
      member do
        patch :best
      end
      resources :comments, only: %i[create], defaults: { commentable: 'answer'}
    end
    resources :comments, only: %i[create], defaults: { commentable: 'question'}
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_many   :links, dependent: :destroy, as: :linkable

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :body, presence: true

  after_commit :send_subscriptions, on: :create

  def mark_as_best
    transaction do
      question.update!(best_answer_id: id)
      question.award&.update!(user: user)
    end
  end

  def best?
    question.best_answer_id == id
  end

  def unmark_as_best
    transaction do
      question.update!(best_answer_id: nil)
      question.award&.update!(user: nil)
    end
  end

  private

  def send_subscriptions
    SubscriptionsJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :answer, only: %i[best destroy]
  after_action  :publish_answer, only: %i[create]
  helper_method :answer, :question

  authorize_resource

  def edit;  end

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = question
    attach_files(@answer)
    @answer.save
  end

  def update
    attach_files(answer)
    answer.update(answer_params)
  end

  def best
    @answer.mark_as_best
  end

  def destroy
    @answer.unmark_as_best if @answer.best?
    @answer.destroy
  end

  private

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, links_attributes: %i[id name url _destroy])
  end

  def attach_files(answer)
    answer.files.attach(params[:answer][:files]) if params[:answer][:files].present?
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("questions/#{@answer.question_id}",
                                 { answer: @answer, links: @answer.links, user: @answer.user.email,
                                   date: @answer.created_at.to_date })
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  before_action :set_answer, only: %i[show update destroy]

  authorize_resource class: Answer

  def index
    @answers = Answer.where(question_id: params[:question_id])
    render json: @answers
  end

  def show
    render json: @answer
  end

  def create
    @answer = current_resource_owner.answers.new(answer_params.merge(question_id: params[:question_id]))

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.destroy
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_answer
    @answer ||= Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  div class = "answer-#{answer.id}"
    p
      .card.mb-2
        .card-header.text-right
            small.text-muted
              ' answered:
              => answer.created_at.to_date
              => answer.user.email
        .row.g-0
          .col-md-2
            = render 'shared/vote', resource: answer
            -if can? :best, answer
              .text-center
                => link_to 'Choose', best_answer_path(answer), remote: true, method: :patch

          .col-md-10
            .card-body
              .card-title
                => answer.body

              .card-text.text-right
                = render partial:'answers/form', locals: {answer: answer}
              .card-text.text-right
                div class = "attachments-#{answer.id}"
                  = render partial: 'attachments/attachments', locals: {resource: answer}
              .card-text.text-right
                div class = "links-#{answer.id}"
                  = render partial: 'links/links', locals: { resource: answer}
              .card-text.text-left
                = render partial: 'comments/comments', locals: {resource: answer}

        .card-footer.text-left
            small.text-muted
              -if can? :edit, answer
                => link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id}
                => link_to 'Delete answer', answer_path(answer), remote: true, method: :delete

app/views/answers/_best_answer.html.slim
- cache best_answer do
  div class = "answer-#{best_answer.id}"
    p
      .card.mb-2
        .card-header.text-right
            small.text-muted
              ' answered:
              => best_answer.created_at.to_date
              => best_answer.user.email
        .row.g-0
          .col-md-2
            .bg-warning
              = render 'shared/vote', resource: best_answer
            .text-center
              b Best answer
          .col-md-10
            .card-body
              .card-title
                => best_answer.body

              .card-text.text-right
                = render partial:'answers/form', locals: {answer: best_answer}
              .card-text.text-right
                div class = "attachments-#{best_answer.id}"
                  = render partial: 'attachments/attachments', locals: {resource: best_answer}
              .card-text.text-right
                div class = "links-#{best_answer.id}"
                  = render partial: 'links/links', locals: { resource: best_answer}
              .card-text.text-left
                = render partial: 'comments/comments', locals: {resource: best_answer}

        .card-footer.text-left
            small.text-muted
              -if can? :edit, best_answer
                => link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: best_answer.id}
                => link_to 'Delete answer', answer_path(best_answer), remote: true, method: :delete

app/views/answers/_form.html.slim
= form_with model: answer, local: false, class: 'd-none', html: {id: "edit-answer-#{answer.id}"} do |f|
  .mb-3.row
    = f.label :body, 'Your answer', class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.text_area :body, class: "form-control"
  .mb-3.row.input-group
    = f.label :files, class: "col-sm-2 col-form-label"
    .col-sm-10
      = f.file_field :files, multiple: true,  class: "input-group-text"
  p
  #links
    = f.fields_for :links do |link|
    .actions
      => link_to_add_association 'add link', f, :links, partial: 'links/link_fields'

  p= f.submit 'Save'

app/views/answers/best.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if !@answer.errors.present? %>
  <% if question.best_answer %>
    $('.answers').html('<%= j render partial: 'answers/best_answer', object: question.best_answer %>')
    $('.answers').append('<%= j render partial: 'answers/answer', collection: question.other_answers, as: :answer %>')
  <% else %>
    $('.answers').html('<%= j render question.answers %>')
  <% end %>
<%end%>

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>")
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer #answer_body').val('')
  $('.new-answer #answer_files').val(null)
<%end%>

app/views/answers/destroy.js.erb
<% if !@answer.persisted? %>
  <% if question.best_answer %>
    $('.answers').html('<%= j render partial: 'answers/best_answer', object: question.best_answer %>')
    $('.answers').append('<%= j render partial: 'answers/answer', collection: question.other_answers, as: :answer %>')
  <% else %>
    $('.answers').html('<%= j render question.answers %>')
  <% end %>
<%end%>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>')

<% if !@answer.errors.present? %>
  <% if question.best_answer %>
    $('.answers').html('<%= j render partial: 'answers/best_answer', object: question.best_answer %>')
    $('.answers').append('<%= j render partial: 'answers/answer', collection: question.other_answers, as: :answer %>')
  <% else %>
    $('.answers').html('<%= j render question.answers %>')
  <% end %>
<%end%>